export {
  BACKGROUND_COLOUR,
  GROUND_COLOUR,
  GROUND_SHADOW,
  WALL_FRAME_COLOUR,
  WALL_FRAME_SHADOW,
  WALL_FRAME_BACKING_COLOUR,
  INK_EDGE_COLOUR,
  SHADOW_OPACITY,
  AMBIENT_INTENSITY,
  DIRECTIONAL_INTENSITY,
} from './colours';

export { SECTIONS, SECTION_DISPLAY_ORDER, TRACK_LENGTH } from './sections';
export type { SectionDefinition } from './sections';
